// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbsyayslqrhztmoycxal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNic3lheXNscXJoenRtb3ljeGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODIwNDAsImV4cCI6MjA3MTA1ODA0MH0.uprhK-yu1fuJNBDru5Mx2AGgJ2sBE0vPby4h5zWi1Qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});